# Generated by Django 5.2.8 on 2025-11-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_borrowrecord_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, default=2003, verbose_name='借閱日期'),
            preserve_default=False,
        ),
    ]
